import selenium.common.exceptions as SE
import pandas as pd
from tqdm import trange
# Need to learn how to use selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Just change it to correspond to the different months.
l_month = ['2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09', '2020-10', '2020-11', '2020-12', '2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12', '2022-01', '2022-02', '2022-03','2022-04','2022-05','2022-06']
l_date_number = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31,30,31,30]

city_dict = { # Just remove all the comments from the following lines
    # 'Aberdeen City': 'Aberdeen',
    # 'Aberdeenshire': 'Aberdeen',
    # 'Adur': 'Shoreham-by-Sea',
    # 'Allerdale': 'Workington',
    # 'Amber Valley': 'Ripley',
    # 'Angus': 'Forfar',
    # 'Antrim and Newtownabbey': 'Antrim',
    # 'Ards and North Down': 'Bangor',
    # 'Argyll and Bute': 'Lochgilphead',
    # 'Armagh City, Banbridge and Craigavon': 'Armagh',
    # 'Arun': 'Littlehampton',
    # 'Ashfield': 'Kirkby-in-Ashfield',
    # 'Ashford': 'Ashford',
    # 'Babergh': 'Ipswich',
    # 'Barking and Dagenham': 'London',
    # 'Barnet': 'London',
    # 'Barnsley': 'Barnsley',
    # 'Barrow-in-Furness': 'Barrow-in-Furness',
    # 'Basildon': 'Basildon',
    # 'Basingstoke and Deane': 'Basingstoke',
    # 'Bassetlaw': 'Worksop',
    # 'Bath and North East Somerset': 'Bath',
    # 'Bedford': 'Bedford',
    # 'Bedfordshire': 'Luton',
    # 'Belfast': 'Belfast',
    # 'Berkshire': 'Reading',
    # 'Berwickshire': 'Duns',
    # 'Bexley': 'London',
    # 'Birmingham': 'Birmingham',
    # 'Blackburn with Darwen': 'Blackburn',
    # 'Blackpool': 'Blackpool',
    # 'Blaenau Gwent': 'Ebbw Vale',
    # 'Bolsover': 'Bolsover',
    # 'Bolton': 'Bolton',
    # 'Boston': 'Boston',
    # 'Bournemouth, Christchurch and Poole': 'Bournemouth',
    # 'Bracknell Forest': 'Bracknell',
    # 'Bradford': 'Bradford',
    # 'Braintree': 'Braintree',
    # 'Breckland': 'Dereham',
    # 'Brent': 'Brent',
    # 'Brentwood': 'Brentwood',
    # 'Bridgend': 'Bridgend',
    # 'Brighton and Hove': 'Brighton',
    # 'Bristol, City of': 'Bristol',
    # 'Broadland': 'Thorpe St Andrew',
    # 'Bromley': 'London',
    # 'Bromsgrove': 'Bromsgrove',
    # 'Broxbourne': 'Broxbourne',
    # 'Broxtowe': 'Broxtowe',
    # 'Buckinghamshire': 'Milton Keynes',
    # 'Burnley': 'Burnley',
    # 'Bury': 'Bury',
    # 'Caerphilly': 'Caerphilly',
    # 'Calderdale': '	Halifax',
    # 'Cambridge': 'Cambridge',
    # 'Camden': 'London',
    # 'Cannock Chase': 'Cannock',
    # 'Canterbury': 'Canterbury',
    # 'Cardiff': 'Cardiff',
    # 'Carlisle': 'Carlisle',
    # 'Carmarthenshire': 'Llanelli',
    # 'Castle Point': 'Thundersley',
    # 'Causeway Coast and Glens': 'Coleraine',
    # 'Central Bedfordshire': 'Chicksands',
    # 'Ceredigion': 'Aberystwyth',
    # 'Charnwood': 'Loughborough',
    # 'Chelmsford': 'Chelmsford',
    # 'Cheltenham': 'Cheltenham',
    # 'Cherwell': 'Birmingham', # Banbury is not the admin HQ of Cherwell.
    # 'Cheshire East': 'Sandbach',
    # 'Cheshire West and Chester': 'Chester',
    # 'Chesterfield': 'Chesterfield',
    # 'Chichester': 'Chichester',
    # 'Chorley': 'Chorley',
    # 'City of Edinburgh': 'Edinburgh',
    # 'City of London': 'London',
    # 'Clackmannanshire': 'Alloa',
    # 'Colchester': 'Colchester',
    # 'Conwy': 'Conwy',
    # 'Copeland': 'Whitehaven',
    # 'Corby': 'Birmingham',
    # 'Cornwall': 'Truro',
    # 'Cotswold': 'Cirencester Abbey',
    # 'County Durham': 'Barnard Castle',
    # 'Coventry': 'Birmingham',
    # 'Craven': 'Skipton',
    # 'Crawley': 'Crawley',
    # 'Croydon': 'London',
    # 'Dacorum': 'London',
    # 'Darlington': 'Darlington',
    # 'Datford': 'Datford',
    # 'Daventry': 'Birmingham',
    # 'Denbighshire': 'Ruthin',
    # 'Derby': 'Derby',
    # 'Derbyshire Dales': 'Matlock',
    # 'Derry City and Strabane': 'Derry',
    # 'Doncaster': 'Doncaster',
    # 'Dorset': 'Dorchester',
    # 'Dover': 'Dover',
    # 'Dudley': 'Dudley',
    # 'Dumfries and Galloway': 'Dumfries',
    # 'Dundee City': 'Dundee',
    # 'Ealing': 'London',
    # 'East Ayrshire': 'Kilmarnock',
    # 'East Cambridgeshire': 'Ely',
    # 'East Devon': 'Newquay',
    # 'East Dunbartonshire': 'Kirkintilloch',
    # 'East Hampshire': 'Petersfield',
    # 'East Hertfordshire': 'Hertford',
    # 'East Lindsey': 'Manby',
    # 'East Lothian': 'Haddington',
    # 'East Northamptonshire': 'Thrapston',
    # 'East Renfrewshire': 'Glasgow',
    # 'East Riding of Yorkshire': 'Beverley',
    # 'East Staffordshire': 'Burton upon Trent',
    # 'East Suffolk': 'Melton',
    # 'Eastbourne': 'Eastbourne',
    # 'Eastleigh': 'Eastleigh',
    # 'Eden': 'Eden',
    # 'Elmbridge': 'Esher',
    # 'Enfield': 'London',
    # 'Epping Forest': 'London',
    # 'Epsom and Ewell': 'Epsom',
    # 'Erewash': 'Ilkeston',
    # 'Exeter': 'Newquay',
    # 'Falkirk': 'Falkirk',
    # 'Fareham': 'Fareham',
    # 'Fenland': 'March',
    # 'Fermanagh and Omagh': 'Omagh',
    # 'Fife': 'Glenrothes',
    # 'Flintshire': 'Mold',
    # 'Folkestone and Hythe': 'Folkestone',
    # 'Forest of Dean': 'Coleford',
    # 'Fylde': 'Lytham St Annes',
    # 'Gateshead': 'Gateshead',
    # 'Gedling': 'Gedling',
    # 'Glasgow City': 'Glasgow',
    # 'Gloucester': 'Gloucester',
    # 'Gosport': 'Gosport',
    # 'Gravesham': 'Gravesend',
    # 'Great Yarmouth': 'Yarmouth',
    # 'Greenwich': 'London',
    # 'Guildford': 'Guildford',
    # 'Gwynedd': 'Gwynedd',
    # 'Hackney': 'London',
    # 'Halton': 'Widnes',
    # 'Hambleton': 'Northallerton',
    # 'Hammersmith and Fulham': 'London',
    # 'Harborough': 'Harborough',
    # 'Haringey': 'London',
    # 'Harlow': 'Harlow',
    # 'Harrogate': 'Harrogate',
    # 'Harrow': 'London',
    # 'Hart': 'Fleet',
    # 'Hartlepool': 'Hartlepool',
    # 'Hastings': 'Hastings',
    # 'Havant': 'Havant',
    # 'Havering': 'London',
    # 'Herefordshire, County of': 'Hereford',
    # 'Hertsmere': 'Borehamwood',
    # 'High Peak': 'Buxton',
    # 'Highland': 'Inverness',
    # 'Hillingdon': 'London',
    # 'Hinckley and Bosworth': 'Leicester',
    # 'Horsham': 'Horsham',
    # 'Hounslow': 'London',
    # 'Huntingdonshire': 'Huntingdon',
    # 'Hyndburn': 'Accrington',
    # 'Inverclyde': 'Greenock',
    # 'Ipswich': 'Ipswich',
    # 'Isle of Anglesey': 'Anglesey',
    # 'Isle of Wight': 'Newport',
    # 'Isle of Scilly': 'Isles of Scilly',
    # 'Islington': 'London',
    # 'Kensington and Chelsea': 'London',
    # 'Kettering': 'Leicester',
    # "King's Lynn and West Norfolk": "King's Lynn",
    # 'Kingston upon Hull, City of': 'Hull',
    # 'Kingston upon Thames': 'London',
    # 'Kirklees': 'Huddersfield',
    # 'Knowsley': 'Knowsley',
    # 'Lambeth': 'London',
    # 'Lancaster': 'Lancaster',
    # 'Leeds': 'Leeds',
    # 'Leicester': 'Leicester',
    # 'Lewes': 'Lewes',
    # 'Lewisham': 'London',
    # 'Lichfield': 'Lichfield',
    # 'Lincoln': 'Lincoln',
    # 'Lisburn and Castlereagh': 'Lisburn',
    # 'Liverpool': 'Liverpool',
    # 'Luton': 'Luton',
    # 'Maidstone': 'Maidstone',
    # 'Maldon': 'Maldon',
    # 'Malvern Hills': 'Great Malvern',
    # 'Manchester': 'Manchester',
    # 'Mansfield': 'Mansfield',
    # 'Medway': 'Medway',
    # 'Melton': 'Melton Mowbray',
    # 'Mendip': 'Shepton Mallet',
    # 'Merthyr Tydfil': 'Merthyr Tydfil',
    'Merton': 'London',
    'Mid and East Antrim': 'Ballymena',
    'Mid Devon': 'Newquay',
    'Mid Suffolk': 'Ipswich',
    'Mid Sussex': 'Haywards Heath',
    'Mid Ulster': 'Cookstown',
    'Middlesbrough': 'Middlesbrough',
    'Midlothian': 'Dalkeith',
    'Milton Keynes': 'Milton Keynes',
    'Mole Valley': 'Dorking',
    'Monmouthshire': 'Monmouthshire',
    'Moray': 'Moray',
    'Na h-Eileanan Siar': 'Stornoway',
    'Neath Port Talbot': 'Port Talbot',
    'New Forest': 'Lyndhurst',
    'Newark and Sherwood': 'Newark-on-Trent',
    'Newcastle upon Tyne': 'Newcastle',
    'Newcastle-under-Lyme': 'Newcastle-under-Lyme',
    'Newham': 'London',
    'Newport': 'Newport',
    'Newry, Mourne and Down': 'Newry',
    'North Ayrshire': 'Irvine',
    'North Devon': 'Newquay',
    'North East Derbyshire': 'Wingerworth',
    'North East Lincolnshire': 'Grimsby',
    'North Hertfordshire': 'Letchworth',
    'North Kesteven': 'Sleaford',
    'North Lanarkshire': 'Motherwell',
    'North Lincolnshire': 'Scunthorpe',
    'North Norfolk': 'Cromer',
    'North Somerset': 'Weston-super-Mare',
    'North Tyneside': 'Wallsend',
    'North Warwickshire': 'Atherstone',
    'North West Leicestershire': 'Coalville',
    'Northampton': 'Leicester',
    'Northumberland': 'Morpeth',
    'Norwich': 'Norwich',
    'Nottingham': 'Nottingham',
    'Nuneaton and Bedworth': 'Birmingham',
    'Oadby and Wigston': 'Wigston Magna',
    'Oldham': 'Manchester',
    'Orkney Islands': 'Orkney',
    'Oxford': 'Oxford',
    'Pembrokeshire': 'Haverfordwest',
    'Pendle': 'Nelson',
    'Perth and Kinross': 'Perth',
    'Peterborough': 'Peterborough',
    'Plymouth': 'Plymouth',
    'Portsmouth': 'Portsmouth',
    'Powys': 'Newtown',
    'Preston': 'Preston',
    'Reading': 'Reading',
    'Redbridge': 'London',
    'Redcar and Cleveland': 'Redcar',
    'Redditch': 'Redditch',
    'Reigate and Banstead': 'Reigate',
    'Renfrewshire': 'Paisley',
    'Rhondda Cynon Taf': 'Clydach Vale',
    'Ribble Valley': 'Clitheroe',
    'Richmond upon Thames': 'London',
    'Rochdale': 'Rochdale',
    'Rochford': 'Rochford',
    'Rossendale': 'Rossendale',
    'Rother': 'Bexhill-on-Sea',
    'Rotherham': 'Rotherham',
    'Rugby': 'Birmingham',
    'Runnymede': 'Addlestone',
    'Rushcliffe': 'West Bridgford',
    'Rushmoor': 'Farnborough',
    'Rutland': 'Oakham',
    'Ryedale': 'Malton',
    'Salford': 'Salford',
    'Sandwell': 'Oldbury',
    'Scarborough': 'Scarborough',
    'Scottish Borders': 'Newtown St Boswells',
    'Sedgemoor': 'Bridgwater',
    'Sefton': 'Sefton',
    'Selby': 'Selby',
    'Sevenoaks': 'Sevenoaks',
    'Sheffield': 'Sheffield',
    'Shetland Islands': 'Shetland',
    'Shropshire': 'Shrewsbury',
    'Slough': 'Slough',
    'Solihull': 'Solihull',
    'Somerset West and Taunton': 'Newquay',
    'South Ayrshire': 'Ayr',
    'South Cambridgeshire': 'Cambourne',
    'South Derbyshire': 'Swadlincote',
    'South Gloucestershire': 'Yate',
    'South Hams': 'Newquay',
    'South Holland': 'Spalding',
    'South Kesteven': 'Grantham',
    'South Lakeland': 'Kendal',
    'South Lanarkshire': 'Hamilton',
    'South Norfolk': 'Norwich',
    'South Northamptonshire': 'Plymouth',
    'South Oxfordshire': 'Milton Park',
    'South Ribble': 'Leyland',
    'South Somerset': 'Yeovil',
    'South Staffordshire': 'Codsall',
    'South Tyneside': 'South Shields',
    'Southwark': 'London',
    'Spelthorne': 'Staines-upon-Thames',
    'St Albans': 'St Albans',
    'St. Helens': 'St. Helens',
    'Stafford': 'Stafford',
    'Staffordshire Moorlands': 'Leek',
    'Stirling': 'Stirling',
    'Stockport': 'Stockport',
    'Stockton-on-Tees': 'Stockton-on-Tees',
    'Stoke-on-Trent': 'Stoke-on-Trent',
    'Stratford-on-Avon': 'Stratford-on-Avon',
    'Stroud': 'Stroud',
    'Sunderland': 'Sunderland',
    'Surrey Heath': 'Camberley',
    'Sutton': 'Sutton',
    'Swale': 'Sittingborne',
    'Swansea': 'Swansea',
    'Swindon': 'Swindon',
    'Tameside': 'Ashton-under-Lyne',
    'Tamworth': 'Tamworth',
    'Tandridge': 'Tandridge',
    'Teignbridge': 'Plymouth',
    'Telford and Wrekin': 'Telford',
    'Tendring': 'Tendring',
    'Test Valley': 'Andover',
    'Tewkesbury': 'Tewkesbury',
    'Thanet': 'Margate',
    'Three Rivers': 'Rickmansworth',
    'Tondridge and Malling': 'West Malling',
    'Torbay': 'Plymouth',
    'Torfaen': 'Pontypool',
    'Torridge': 'Newquay',
    'Tower Hamlets': 'London',
    'Trafford': 'Manchester',
    'Tunbridge Wells': 'Royal Tunbridge Wells',
    'Uttlesford': 'Saffron Walden',
    'Vale of Glamorgan': 'Barry',
    'Vale of White Horse': 'Abingdon-on-Thames',
    'Wakefield': 'Wakefield',
    'Walsall': 'Walsall',
    'Waltham Forest': 'London',
    'Wandsworth': 'London',
    'Warrington': 'Warrington',
    'Warwick': 'Birmingham',
    'Watford': 'Watford',
    'Waverley': 'Waverley',
    'Wealden': 'Hailsham',
    'Wellingborough': 'Wellingborough',
    'Welwyn Hatfield': 'Welwyn Garden City',
    'West Berkshire': 'Newbury',
    'West Devon': 'Newquay',
    'West Dunbartonshire': 'Dumbarton',
    'West Lancashire': 'Ormskirk',
    'West Lindsey': 'Gainsborough',
    'West Lothian': 'Livingstone',
    'West Oxfordshire': 'Witney',
    'West Suffolk': 'Bury St Edmunds',
    'Westminster': 'London',
    'Wigan': 'Wigan',
    'Wiltshire': 'Trowbridge',
    'Winchester': 'Winchester',
    'Windsor and Maidenhead': 'Maidenhead',
    'Wirral': 'Wallasey',
    'Woking': 'Woking',
    'Wokingham': 'Wokingham',
    'Wolverhampton': 'Wolverhampton',
    'Worchester': 'Worchester',
    'Worthing': 'Worthing',
    'Wrexham': 'Wrexham',
    'Wychavon': 'Pershore',
    'Wyre Forest': 'Kidderminster',
    'Wyre': 'Poulton-le-Fylde',
    'York': 'York',
}

city_list = sorted(list(city_dict.keys()))

# from 2020-2-1 to 2021-3-31
for dist in city_list:
    city = city_dict[dist]
    options = Options()
    options.headless = True
    driver = webdriver.Chrome(options=options)

    matrix = []
    for index in trange(len(l_month)):
        driver.get("https://www.wunderground.com/history/monthly/gb/{}/date/{}".format('-'.join(city.split()), l_month[index]))
        try:
            for i in range(l_date_number[index]):
                first_timeout = 60
                default_timeout = 10
                date = WebDriverWait(driver, timeout=first_timeout).until(
                        EC.presence_of_element_located((By.CSS_SELECTOR, '#inner-content > div.region-content-main > div.row > div:nth-child(5) > div:nth-child(1) > div > lib-city-history-observation > div > div.observation-table.ng-star-inserted > table > tbody > tr > td:nth-child(1) > table > tr:nth-child({}) > td'.format(i + 2)))
                    ).text.strip()
                if i > 5 and date == '1': # 5 is a custom threshold
                    continue
                row = []
                row.append('{}-{}-{}'.format(l_month[index].split('-')[0], l_month[index].split('-')[1].rjust(2, '0'), str(date).rjust(2, '0')))
                for j in range(2, 7):
                    # 2 - temperature (°F)
                    # 3 - dew point (°F)
                    # 4 - humidity (%)
                    # 5 - wind speed (mph)
                    # 6 - pressure (inHg)
                    element = WebDriverWait(driver, timeout=default_timeout).until(
                        EC.presence_of_element_located((By.XPATH, '//*[@id="inner-content"]/div[2]/div[1]/div[5]/div[1]/div/lib-city-history-observation/div/div[2]/table/tbody/tr/td[{}]/table/tr[{}]/td[2]'.format(j, i + 2)))
                    )
                    row.append(
                        element.text.strip()
                    )
                # precpitation (in)
                element = WebDriverWait(driver, timeout=default_timeout).until(
                        EC.presence_of_element_located((By.XPATH, '//*[@id="inner-content"]/div[2]/div[1]/div[5]/div[1]/div/lib-city-history-observation/div/div[2]/table/tbody/tr/td[7]/table/tr[{}]/td'.format(i + 2)))
                    )
                row.append(
                        element.text.strip()
                )
                matrix.append(row)
        except (SE.NoSuchElementException, SE.TimeoutException, SE.WebDriverException):
            pass

    driver.close()
    df = pd.DataFrame(matrix, columns = ['Date', 'Temperature (°F)', 'Dew Point (°F)', 'Humidity (%)', 'Wind Speed (mph)', 'Pressure (inHg)', 'Precipitation (in)'])
    df.to_csv('C:\\Users\\13955\\gitee\\Ruize_repository\\2022-summer\\data\\weather\\{}.csv'.format(dist.title()), index = False) # Here you need to change the path


